/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as AgencyAdminRouteImport } from './routes/agency-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as SuperAdminUsersIndexRouteImport } from './routes/super-admin/users/index'
import { Route as SuperAdminTeamsIndexRouteImport } from './routes/super-admin/teams/index'
import { Route as SuperAdminLocationsIndexRouteImport } from './routes/super-admin/locations/index'
import { Route as SuperAdminAgenciesIndexRouteImport } from './routes/super-admin/agencies/index'
import { Route as SuperAdminTeamsCreateRouteImport } from './routes/super-admin/teams/create'
import { Route as SuperAdminLocationsCreateRouteImport } from './routes/super-admin/locations/create'
import { Route as SuperAdminAgenciesIdRouteImport } from './routes/super-admin/agencies/$id'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyAdminRoute = AgencyAdminRouteImport.update({
  id: '/agency-admin',
  path: '/agency-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminUsersIndexRoute = SuperAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminTeamsIndexRoute = SuperAdminTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminLocationsIndexRoute =
  SuperAdminLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminAgenciesIndexRoute = SuperAdminAgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminTeamsCreateRoute = SuperAdminTeamsCreateRouteImport.update({
  id: '/teams/create',
  path: '/teams/create',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminLocationsCreateRoute =
  SuperAdminLocationsCreateRouteImport.update({
    id: '/locations/create',
    path: '/locations/create',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminAgenciesIdRoute = SuperAdminAgenciesIdRouteImport.update({
  id: '/agencies/$id',
  path: '/agencies/$id',
  getParentRoute: () => SuperAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency-admin': typeof AgencyAdminRoute
  '/officer': typeof OfficerRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/docs': typeof DocsIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/super-admin/agencies/$id': typeof SuperAdminAgenciesIdRoute
  '/super-admin/locations/create': typeof SuperAdminLocationsCreateRoute
  '/super-admin/teams/create': typeof SuperAdminTeamsCreateRoute
  '/super-admin/agencies': typeof SuperAdminAgenciesIndexRoute
  '/super-admin/locations': typeof SuperAdminLocationsIndexRoute
  '/super-admin/teams': typeof SuperAdminTeamsIndexRoute
  '/super-admin/users': typeof SuperAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency-admin': typeof AgencyAdminRoute
  '/officer': typeof OfficerRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/docs': typeof DocsIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/super-admin/agencies/$id': typeof SuperAdminAgenciesIdRoute
  '/super-admin/locations/create': typeof SuperAdminLocationsCreateRoute
  '/super-admin/teams/create': typeof SuperAdminTeamsCreateRoute
  '/super-admin/agencies': typeof SuperAdminAgenciesIndexRoute
  '/super-admin/locations': typeof SuperAdminLocationsIndexRoute
  '/super-admin/teams': typeof SuperAdminTeamsIndexRoute
  '/super-admin/users': typeof SuperAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency-admin': typeof AgencyAdminRoute
  '/officer': typeof OfficerRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/docs/': typeof DocsIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/super-admin/agencies/$id': typeof SuperAdminAgenciesIdRoute
  '/super-admin/locations/create': typeof SuperAdminLocationsCreateRoute
  '/super-admin/teams/create': typeof SuperAdminTeamsCreateRoute
  '/super-admin/agencies/': typeof SuperAdminAgenciesIndexRoute
  '/super-admin/locations/': typeof SuperAdminLocationsIndexRoute
  '/super-admin/teams/': typeof SuperAdminTeamsIndexRoute
  '/super-admin/users/': typeof SuperAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency-admin'
    | '/officer'
    | '/super-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/docs'
    | '/super-admin/'
    | '/super-admin/agencies/$id'
    | '/super-admin/locations/create'
    | '/super-admin/teams/create'
    | '/super-admin/agencies'
    | '/super-admin/locations'
    | '/super-admin/teams'
    | '/super-admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency-admin'
    | '/officer'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/docs'
    | '/super-admin'
    | '/super-admin/agencies/$id'
    | '/super-admin/locations/create'
    | '/super-admin/teams/create'
    | '/super-admin/agencies'
    | '/super-admin/locations'
    | '/super-admin/teams'
    | '/super-admin/users'
  id:
    | '__root__'
    | '/'
    | '/agency-admin'
    | '/officer'
    | '/super-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/docs/'
    | '/super-admin/'
    | '/super-admin/agencies/$id'
    | '/super-admin/locations/create'
    | '/super-admin/teams/create'
    | '/super-admin/agencies/'
    | '/super-admin/locations/'
    | '/super-admin/teams/'
    | '/super-admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyAdminRoute: typeof AgencyAdminRoute
  OfficerRoute: typeof OfficerRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-admin': {
      id: '/agency-admin'
      path: '/agency-admin'
      fullPath: '/agency-admin'
      preLoaderRoute: typeof AgencyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/users/': {
      id: '/super-admin/users/'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/teams/': {
      id: '/super-admin/teams/'
      path: '/teams'
      fullPath: '/super-admin/teams'
      preLoaderRoute: typeof SuperAdminTeamsIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/locations/': {
      id: '/super-admin/locations/'
      path: '/locations'
      fullPath: '/super-admin/locations'
      preLoaderRoute: typeof SuperAdminLocationsIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/agencies/': {
      id: '/super-admin/agencies/'
      path: '/agencies'
      fullPath: '/super-admin/agencies'
      preLoaderRoute: typeof SuperAdminAgenciesIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/teams/create': {
      id: '/super-admin/teams/create'
      path: '/teams/create'
      fullPath: '/super-admin/teams/create'
      preLoaderRoute: typeof SuperAdminTeamsCreateRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/locations/create': {
      id: '/super-admin/locations/create'
      path: '/locations/create'
      fullPath: '/super-admin/locations/create'
      preLoaderRoute: typeof SuperAdminLocationsCreateRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/agencies/$id': {
      id: '/super-admin/agencies/$id'
      path: '/agencies/$id'
      fullPath: '/super-admin/agencies/$id'
      preLoaderRoute: typeof SuperAdminAgenciesIdRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
  SuperAdminAgenciesIdRoute: typeof SuperAdminAgenciesIdRoute
  SuperAdminLocationsCreateRoute: typeof SuperAdminLocationsCreateRoute
  SuperAdminTeamsCreateRoute: typeof SuperAdminTeamsCreateRoute
  SuperAdminAgenciesIndexRoute: typeof SuperAdminAgenciesIndexRoute
  SuperAdminLocationsIndexRoute: typeof SuperAdminLocationsIndexRoute
  SuperAdminTeamsIndexRoute: typeof SuperAdminTeamsIndexRoute
  SuperAdminUsersIndexRoute: typeof SuperAdminUsersIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminIndexRoute: SuperAdminIndexRoute,
  SuperAdminAgenciesIdRoute: SuperAdminAgenciesIdRoute,
  SuperAdminLocationsCreateRoute: SuperAdminLocationsCreateRoute,
  SuperAdminTeamsCreateRoute: SuperAdminTeamsCreateRoute,
  SuperAdminAgenciesIndexRoute: SuperAdminAgenciesIndexRoute,
  SuperAdminLocationsIndexRoute: SuperAdminLocationsIndexRoute,
  SuperAdminTeamsIndexRoute: SuperAdminTeamsIndexRoute,
  SuperAdminUsersIndexRoute: SuperAdminUsersIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyAdminRoute: AgencyAdminRoute,
  OfficerRoute: OfficerRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
