/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as AgencyAdminRouteImport } from './routes/agency-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as OfficerIndexRouteImport } from './routes/officer/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AgencyAdminIndexRouteImport } from './routes/agency-admin/index'
import { Route as OfficerProfileRouteImport } from './routes/officer/profile'
import { Route as DocsSearchAndFiltersRouteImport } from './routes/docs/search-and-filters'
import { Route as DocsRolesAndPermissionsRouteImport } from './routes/docs/roles-and-permissions'
import { Route as DocsMobileRouteImport } from './routes/docs/mobile'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsCasesRouteImport } from './routes/docs/cases'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as SuperAdminUsersIndexRouteImport } from './routes/super-admin/users/index'
import { Route as SuperAdminTeamsIndexRouteImport } from './routes/super-admin/teams/index'
import { Route as SuperAdminLocationsIndexRouteImport } from './routes/super-admin/locations/index'
import { Route as SuperAdminAgenciesIndexRouteImport } from './routes/super-admin/agencies/index'
import { Route as OfficerReportsIndexRouteImport } from './routes/officer/reports/index'
import { Route as AgencyAdminTeamsIndexRouteImport } from './routes/agency-admin/teams/index'
import { Route as AgencyAdminLocationsIndexRouteImport } from './routes/agency-admin/locations/index'
import { Route as SuperAdminTeamsCreateRouteImport } from './routes/super-admin/teams/create'
import { Route as SuperAdminLocationsCreateRouteImport } from './routes/super-admin/locations/create'
import { Route as SuperAdminAgenciesIdRouteImport } from './routes/super-admin/agencies/$id'
import { Route as OfficerReportsCreateRouteImport } from './routes/officer/reports/create'
import { Route as OfficerReportsIdRouteImport } from './routes/officer/reports/$id'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyAdminRoute = AgencyAdminRouteImport.update({
  id: '/agency-admin',
  path: '/agency-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyAdminIndexRoute = AgencyAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgencyAdminRoute,
} as any)
const OfficerProfileRoute = OfficerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OfficerRoute,
} as any)
const DocsSearchAndFiltersRoute = DocsSearchAndFiltersRouteImport.update({
  id: '/docs/search-and-filters',
  path: '/docs/search-and-filters',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRolesAndPermissionsRoute = DocsRolesAndPermissionsRouteImport.update({
  id: '/docs/roles-and-permissions',
  path: '/docs/roles-and-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMobileRoute = DocsMobileRouteImport.update({
  id: '/docs/mobile',
  path: '/docs/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/docs/getting-started',
  path: '/docs/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCasesRoute = DocsCasesRouteImport.update({
  id: '/docs/cases',
  path: '/docs/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminUsersIndexRoute = SuperAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminTeamsIndexRoute = SuperAdminTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminLocationsIndexRoute =
  SuperAdminLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminAgenciesIndexRoute = SuperAdminAgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const OfficerReportsIndexRoute = OfficerReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => OfficerRoute,
} as any)
const AgencyAdminTeamsIndexRoute = AgencyAdminTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AgencyAdminRoute,
} as any)
const AgencyAdminLocationsIndexRoute =
  AgencyAdminLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AgencyAdminRoute,
  } as any)
const SuperAdminTeamsCreateRoute = SuperAdminTeamsCreateRouteImport.update({
  id: '/teams/create',
  path: '/teams/create',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminLocationsCreateRoute =
  SuperAdminLocationsCreateRouteImport.update({
    id: '/locations/create',
    path: '/locations/create',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminAgenciesIdRoute = SuperAdminAgenciesIdRouteImport.update({
  id: '/agencies/$id',
  path: '/agencies/$id',
  getParentRoute: () => SuperAdminRoute,
} as any)
const OfficerReportsCreateRoute = OfficerReportsCreateRouteImport.update({
  id: '/reports/create',
  path: '/reports/create',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerReportsIdRoute = OfficerReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => OfficerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency-admin': typeof AgencyAdminRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/docs/cases': typeof DocsCasesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/mobile': typeof DocsMobileRoute
  '/docs/roles-and-permissions': typeof DocsRolesAndPermissionsRoute
  '/docs/search-and-filters': typeof DocsSearchAndFiltersRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/agency-admin/': typeof AgencyAdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/officer/reports/$id': typeof OfficerReportsIdRoute
  '/officer/reports/create': typeof OfficerReportsCreateRoute
  '/super-admin/agencies/$id': typeof SuperAdminAgenciesIdRoute
  '/super-admin/locations/create': typeof SuperAdminLocationsCreateRoute
  '/super-admin/teams/create': typeof SuperAdminTeamsCreateRoute
  '/agency-admin/locations': typeof AgencyAdminLocationsIndexRoute
  '/agency-admin/teams': typeof AgencyAdminTeamsIndexRoute
  '/officer/reports': typeof OfficerReportsIndexRoute
  '/super-admin/agencies': typeof SuperAdminAgenciesIndexRoute
  '/super-admin/locations': typeof SuperAdminLocationsIndexRoute
  '/super-admin/teams': typeof SuperAdminTeamsIndexRoute
  '/super-admin/users': typeof SuperAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/docs/cases': typeof DocsCasesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/mobile': typeof DocsMobileRoute
  '/docs/roles-and-permissions': typeof DocsRolesAndPermissionsRoute
  '/docs/search-and-filters': typeof DocsSearchAndFiltersRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/agency-admin': typeof AgencyAdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/officer/reports/$id': typeof OfficerReportsIdRoute
  '/officer/reports/create': typeof OfficerReportsCreateRoute
  '/super-admin/agencies/$id': typeof SuperAdminAgenciesIdRoute
  '/super-admin/locations/create': typeof SuperAdminLocationsCreateRoute
  '/super-admin/teams/create': typeof SuperAdminTeamsCreateRoute
  '/agency-admin/locations': typeof AgencyAdminLocationsIndexRoute
  '/agency-admin/teams': typeof AgencyAdminTeamsIndexRoute
  '/officer/reports': typeof OfficerReportsIndexRoute
  '/super-admin/agencies': typeof SuperAdminAgenciesIndexRoute
  '/super-admin/locations': typeof SuperAdminLocationsIndexRoute
  '/super-admin/teams': typeof SuperAdminTeamsIndexRoute
  '/super-admin/users': typeof SuperAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency-admin': typeof AgencyAdminRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/docs/cases': typeof DocsCasesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/mobile': typeof DocsMobileRoute
  '/docs/roles-and-permissions': typeof DocsRolesAndPermissionsRoute
  '/docs/search-and-filters': typeof DocsSearchAndFiltersRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/agency-admin/': typeof AgencyAdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/officer/reports/$id': typeof OfficerReportsIdRoute
  '/officer/reports/create': typeof OfficerReportsCreateRoute
  '/super-admin/agencies/$id': typeof SuperAdminAgenciesIdRoute
  '/super-admin/locations/create': typeof SuperAdminLocationsCreateRoute
  '/super-admin/teams/create': typeof SuperAdminTeamsCreateRoute
  '/agency-admin/locations/': typeof AgencyAdminLocationsIndexRoute
  '/agency-admin/teams/': typeof AgencyAdminTeamsIndexRoute
  '/officer/reports/': typeof OfficerReportsIndexRoute
  '/super-admin/agencies/': typeof SuperAdminAgenciesIndexRoute
  '/super-admin/locations/': typeof SuperAdminLocationsIndexRoute
  '/super-admin/teams/': typeof SuperAdminTeamsIndexRoute
  '/super-admin/users/': typeof SuperAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency-admin'
    | '/officer'
    | '/super-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/docs/cases'
    | '/docs/getting-started'
    | '/docs/mobile'
    | '/docs/roles-and-permissions'
    | '/docs/search-and-filters'
    | '/officer/profile'
    | '/agency-admin/'
    | '/docs'
    | '/officer/'
    | '/super-admin/'
    | '/officer/reports/$id'
    | '/officer/reports/create'
    | '/super-admin/agencies/$id'
    | '/super-admin/locations/create'
    | '/super-admin/teams/create'
    | '/agency-admin/locations'
    | '/agency-admin/teams'
    | '/officer/reports'
    | '/super-admin/agencies'
    | '/super-admin/locations'
    | '/super-admin/teams'
    | '/super-admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/docs/cases'
    | '/docs/getting-started'
    | '/docs/mobile'
    | '/docs/roles-and-permissions'
    | '/docs/search-and-filters'
    | '/officer/profile'
    | '/agency-admin'
    | '/docs'
    | '/officer'
    | '/super-admin'
    | '/officer/reports/$id'
    | '/officer/reports/create'
    | '/super-admin/agencies/$id'
    | '/super-admin/locations/create'
    | '/super-admin/teams/create'
    | '/agency-admin/locations'
    | '/agency-admin/teams'
    | '/officer/reports'
    | '/super-admin/agencies'
    | '/super-admin/locations'
    | '/super-admin/teams'
    | '/super-admin/users'
  id:
    | '__root__'
    | '/'
    | '/agency-admin'
    | '/officer'
    | '/super-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/docs/cases'
    | '/docs/getting-started'
    | '/docs/mobile'
    | '/docs/roles-and-permissions'
    | '/docs/search-and-filters'
    | '/officer/profile'
    | '/agency-admin/'
    | '/docs/'
    | '/officer/'
    | '/super-admin/'
    | '/officer/reports/$id'
    | '/officer/reports/create'
    | '/super-admin/agencies/$id'
    | '/super-admin/locations/create'
    | '/super-admin/teams/create'
    | '/agency-admin/locations/'
    | '/agency-admin/teams/'
    | '/officer/reports/'
    | '/super-admin/agencies/'
    | '/super-admin/locations/'
    | '/super-admin/teams/'
    | '/super-admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyAdminRoute: typeof AgencyAdminRouteWithChildren
  OfficerRoute: typeof OfficerRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DocsCasesRoute: typeof DocsCasesRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsMobileRoute: typeof DocsMobileRoute
  DocsRolesAndPermissionsRoute: typeof DocsRolesAndPermissionsRoute
  DocsSearchAndFiltersRoute: typeof DocsSearchAndFiltersRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-admin': {
      id: '/agency-admin'
      path: '/agency-admin'
      fullPath: '/agency-admin'
      preLoaderRoute: typeof AgencyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-admin/': {
      id: '/agency-admin/'
      path: '/'
      fullPath: '/agency-admin/'
      preLoaderRoute: typeof AgencyAdminIndexRouteImport
      parentRoute: typeof AgencyAdminRoute
    }
    '/officer/profile': {
      id: '/officer/profile'
      path: '/profile'
      fullPath: '/officer/profile'
      preLoaderRoute: typeof OfficerProfileRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/docs/search-and-filters': {
      id: '/docs/search-and-filters'
      path: '/docs/search-and-filters'
      fullPath: '/docs/search-and-filters'
      preLoaderRoute: typeof DocsSearchAndFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/roles-and-permissions': {
      id: '/docs/roles-and-permissions'
      path: '/docs/roles-and-permissions'
      fullPath: '/docs/roles-and-permissions'
      preLoaderRoute: typeof DocsRolesAndPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mobile': {
      id: '/docs/mobile'
      path: '/docs/mobile'
      fullPath: '/docs/mobile'
      preLoaderRoute: typeof DocsMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/docs/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cases': {
      id: '/docs/cases'
      path: '/docs/cases'
      fullPath: '/docs/cases'
      preLoaderRoute: typeof DocsCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/users/': {
      id: '/super-admin/users/'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/teams/': {
      id: '/super-admin/teams/'
      path: '/teams'
      fullPath: '/super-admin/teams'
      preLoaderRoute: typeof SuperAdminTeamsIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/locations/': {
      id: '/super-admin/locations/'
      path: '/locations'
      fullPath: '/super-admin/locations'
      preLoaderRoute: typeof SuperAdminLocationsIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/agencies/': {
      id: '/super-admin/agencies/'
      path: '/agencies'
      fullPath: '/super-admin/agencies'
      preLoaderRoute: typeof SuperAdminAgenciesIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/officer/reports/': {
      id: '/officer/reports/'
      path: '/reports'
      fullPath: '/officer/reports'
      preLoaderRoute: typeof OfficerReportsIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/agency-admin/teams/': {
      id: '/agency-admin/teams/'
      path: '/teams'
      fullPath: '/agency-admin/teams'
      preLoaderRoute: typeof AgencyAdminTeamsIndexRouteImport
      parentRoute: typeof AgencyAdminRoute
    }
    '/agency-admin/locations/': {
      id: '/agency-admin/locations/'
      path: '/locations'
      fullPath: '/agency-admin/locations'
      preLoaderRoute: typeof AgencyAdminLocationsIndexRouteImport
      parentRoute: typeof AgencyAdminRoute
    }
    '/super-admin/teams/create': {
      id: '/super-admin/teams/create'
      path: '/teams/create'
      fullPath: '/super-admin/teams/create'
      preLoaderRoute: typeof SuperAdminTeamsCreateRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/locations/create': {
      id: '/super-admin/locations/create'
      path: '/locations/create'
      fullPath: '/super-admin/locations/create'
      preLoaderRoute: typeof SuperAdminLocationsCreateRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/agencies/$id': {
      id: '/super-admin/agencies/$id'
      path: '/agencies/$id'
      fullPath: '/super-admin/agencies/$id'
      preLoaderRoute: typeof SuperAdminAgenciesIdRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/officer/reports/create': {
      id: '/officer/reports/create'
      path: '/reports/create'
      fullPath: '/officer/reports/create'
      preLoaderRoute: typeof OfficerReportsCreateRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/reports/$id': {
      id: '/officer/reports/$id'
      path: '/reports/$id'
      fullPath: '/officer/reports/$id'
      preLoaderRoute: typeof OfficerReportsIdRouteImport
      parentRoute: typeof OfficerRoute
    }
  }
}

interface AgencyAdminRouteChildren {
  AgencyAdminIndexRoute: typeof AgencyAdminIndexRoute
  AgencyAdminLocationsIndexRoute: typeof AgencyAdminLocationsIndexRoute
  AgencyAdminTeamsIndexRoute: typeof AgencyAdminTeamsIndexRoute
}

const AgencyAdminRouteChildren: AgencyAdminRouteChildren = {
  AgencyAdminIndexRoute: AgencyAdminIndexRoute,
  AgencyAdminLocationsIndexRoute: AgencyAdminLocationsIndexRoute,
  AgencyAdminTeamsIndexRoute: AgencyAdminTeamsIndexRoute,
}

const AgencyAdminRouteWithChildren = AgencyAdminRoute._addFileChildren(
  AgencyAdminRouteChildren,
)

interface OfficerRouteChildren {
  OfficerProfileRoute: typeof OfficerProfileRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerReportsIdRoute: typeof OfficerReportsIdRoute
  OfficerReportsCreateRoute: typeof OfficerReportsCreateRoute
  OfficerReportsIndexRoute: typeof OfficerReportsIndexRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerProfileRoute: OfficerProfileRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerReportsIdRoute: OfficerReportsIdRoute,
  OfficerReportsCreateRoute: OfficerReportsCreateRoute,
  OfficerReportsIndexRoute: OfficerReportsIndexRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
  SuperAdminAgenciesIdRoute: typeof SuperAdminAgenciesIdRoute
  SuperAdminLocationsCreateRoute: typeof SuperAdminLocationsCreateRoute
  SuperAdminTeamsCreateRoute: typeof SuperAdminTeamsCreateRoute
  SuperAdminAgenciesIndexRoute: typeof SuperAdminAgenciesIndexRoute
  SuperAdminLocationsIndexRoute: typeof SuperAdminLocationsIndexRoute
  SuperAdminTeamsIndexRoute: typeof SuperAdminTeamsIndexRoute
  SuperAdminUsersIndexRoute: typeof SuperAdminUsersIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminIndexRoute: SuperAdminIndexRoute,
  SuperAdminAgenciesIdRoute: SuperAdminAgenciesIdRoute,
  SuperAdminLocationsCreateRoute: SuperAdminLocationsCreateRoute,
  SuperAdminTeamsCreateRoute: SuperAdminTeamsCreateRoute,
  SuperAdminAgenciesIndexRoute: SuperAdminAgenciesIndexRoute,
  SuperAdminLocationsIndexRoute: SuperAdminLocationsIndexRoute,
  SuperAdminTeamsIndexRoute: SuperAdminTeamsIndexRoute,
  SuperAdminUsersIndexRoute: SuperAdminUsersIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyAdminRoute: AgencyAdminRouteWithChildren,
  OfficerRoute: OfficerRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DocsCasesRoute: DocsCasesRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsMobileRoute: DocsMobileRoute,
  DocsRolesAndPermissionsRoute: DocsRolesAndPermissionsRoute,
  DocsSearchAndFiltersRoute: DocsSearchAndFiltersRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
