import { createClient } from '@/lib/supabase/server';
import { NextResponse } from 'next/server';

export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = await createClient();
    const { id } = params;

    // Get document details
    const { data: document, error } = await supabase
      .from('documents')
      .select(`
        *,
        template:document_templates(name, type, template_content)
      `)
      .eq('id', id)
      .single();

    if (error) throw error;

    // Generate PDF from HTML content
    // In production, use a library like puppeteer, jsPDF, or @react-pdf/renderer
    const pdfHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { 
            font-family: Arial, sans-serif; 
            padding: 40px;
            line-height: 1.6;
          }
          .header { 
            text-align: center; 
            margin-bottom: 40px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
          }
          .document-number { 
            font-size: 14px; 
            color: #666;
            margin-bottom: 10px;
          }
          .title { 
            font-size: 24px; 
            font-weight: bold; 
            color: #333;
          }
          .content { 
            margin: 20px 0;
          }
          .footer { 
            margin-top: 60px; 
            padding-top: 20px;
            border-top: 1px solid #ccc;
            text-align: center; 
            color: #666; 
            font-size: 12px;
          }
          .signature-section {
            margin-top: 80px;
            display: flex;
            justify-content: space-between;
          }
          .signature-box {
            width: 40%;
          }
          .signature-line {
            border-top: 1px solid #333;
            margin-top: 60px;
            padding-top: 10px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="document-number">Document No: ${document.document_number}</div>
          <div class="title">${document.title}</div>
          <div class="document-number">Generated: ${new Date(document.created_at).toLocaleDateString()}</div>
        </div>
        
        <div class="content">
          ${document.content}
        </div>
        
        <div class="signature-section">
          <div class="signature-box">
            <div class="signature-line">
              <strong>Authorized Officer</strong><br>
              Name: _____________________<br>
              Date: _____________________
            </div>
          </div>
          <div class="signature-box">
            <div class="signature-line">
              <strong>Recipient</strong><br>
              Name: _____________________<br>
              Date: _____________________
            </div>
          </div>
        </div>
        
        <div class="footer">
          <p>This is an official document generated by MANTIS</p>
          <p>Document ID: ${document.id}</p>
        </div>
      </body>
      </html>
    `;

    // Return HTML that can be converted to PDF on client
    // In production, server-side PDF generation is recommended
    return new NextResponse(pdfHtml, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="${document.document_number}.html"`,
      },
    });
  } catch (error) {
    console.error('Error generating PDF:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}
