/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemInitRouteImport } from './routes/system-init'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InfringementsRouteImport } from './routes/infringements'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as IndexRouteImport } from './routes/index'

const SystemInitRoute = SystemInitRouteImport.update({
  id: '/system-init',
  path: '/system-init',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InfringementsRoute = InfringementsRouteImport.update({
  id: '/infringements',
  path: '/infringements',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disputes': typeof DisputesRoute
  '/infringements': typeof InfringementsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/system-init': typeof SystemInitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disputes': typeof DisputesRoute
  '/infringements': typeof InfringementsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/system-init': typeof SystemInitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disputes': typeof DisputesRoute
  '/infringements': typeof InfringementsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/system-init': typeof SystemInitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disputes'
    | '/infringements'
    | '/login'
    | '/payments'
    | '/reports'
    | '/system-init'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disputes'
    | '/infringements'
    | '/login'
    | '/payments'
    | '/reports'
    | '/system-init'
  id:
    | '__root__'
    | '/'
    | '/disputes'
    | '/infringements'
    | '/login'
    | '/payments'
    | '/reports'
    | '/system-init'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisputesRoute: typeof DisputesRoute
  InfringementsRoute: typeof InfringementsRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  SystemInitRoute: typeof SystemInitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-init': {
      id: '/system-init'
      path: '/system-init'
      fullPath: '/system-init'
      preLoaderRoute: typeof SystemInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infringements': {
      id: '/infringements'
      path: '/infringements'
      fullPath: '/infringements'
      preLoaderRoute: typeof InfringementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisputesRoute: DisputesRoute,
  InfringementsRoute: InfringementsRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  SystemInitRoute: SystemInitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
